
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - permission-bot.mrriptide.github.io
  resources:
  - permissionbots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - permission-bot.mrriptide.github.io
  resources:
  - permissionbots/finalizers
  verbs:
  - update
- apiGroups:
  - permission-bot.mrriptide.github.io
  resources:
  - permissionbots/status
  verbs:
  - get
  - patch
  - update
